app:
  name : UserService
  log.tomcat-version : true

logging.level.org.repl.springcloud: ${USER_SERVICE_LOGGING_LEVEL:DEBUG}

server:
  port: ${port:9090}
  compression:
    enabled: false
    mime-types: application/json, text/html
    min-response-size: 2048

spring:
  application:
    name: user-service
  cloud:
    config:
      discovery:
        enabled: true
      fail-fast: true
      retry:
        multiplier: 2
        max-interval: 60000
        max-attempts: 3840
  jackson:
    serialization:
      indent_output: false
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: qwerty123
      database: user_db
      port: 27017
      host: localhost

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY}

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  http:
    client:
      enabled: true

jwt.signing.key: dev-signing-key:change it
